# Generated by Django 5.1.1 on 2024-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lend_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approver",
            name="profile_image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
