# Generated by Django 5.1.1 on 2024-10-08 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lend_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="category",
            new_name="categories",
        ),
    ]
