# Generated by Django 5.1.1 on 2024-10-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lend_app", "0002_rename_category_item_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrequest",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lend_app.approver",
            ),
        ),
    ]
