# Generated by Django 5.1.1 on 2024-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lend_app", "0002_alter_approver_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="profile_image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
